# Generated by Django 4.2 on 2023-05-01 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('ratio', models.FloatField(default=1)),
                ('emission_factor', models.FloatField(blank=True, null=True)),
                ('total_emission', models.FloatField(blank=True, help_text='Unit in kg', null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('acquisition_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lifetime', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.source')),
            ],
        ),
    ]
