# Generated by Django 4.2 on 2023-05-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_modification'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='delta',
            field=models.FloatField(default=0),
        ),
    ]
