# Generated by Django 4.2 on 2023-05-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_source_delta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='delta',
        ),
    ]
