# Generated by Django 4.2 on 2023-06-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_source_delta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modification',
            name='acquisition_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
